In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import scale
from sklearn.svm import SVC

In [2]:
df = pd.read_csv('data/pulsar_data.csv')
df.head()

Mean of the integrated profile  \
0                       121.156250   
1                        76.968750   
2                       130.585938   
3                       156.398438   
4                        84.804688   

    Standard deviation of the integrated profile  \
0                                      48.372971   
1                                      36.175557   
2                                      53.229534   
3                                      48.865942   
4                                      36.117659   

    Excess kurtosis of the integrated profile  \
0                                    0.375485   
1                                    0.712898   
2                                    0.133408   
3                                   -0.215989   
4                                    0.825013   

    Skewness of the integrated profile   Mean of the DM-SNR curve  \
0                            -0.013165                   3.168896   
1                             3.388719                   2.399666   
2                            -0.297242                   2.743311   
3                            -0.171294                  17.471572   
4                             3.274125                   2.790134   

    Standard deviation of the DM-SNR curve  \
0                                18.399367   
1                                17.570997   
2                                22.362553   
3                                      NaN   
4                                20.618009   

    Excess kurtosis of the DM-SNR curve   Skewness of the DM-SNR curve  \
0                              7.449874                      65.159298   
1                              9.414652                     102.722975   
2                              8.508364                      74.031324   
3                              2.958066                       7.197842   
4                              8.405008                      76.291128   

   target_class  
0           0.0  
1           0.0  
2           0.0  
3           0.0  
4           0.0

In [3]:
df.shape

(12528, 9)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12528 entries, 0 to 12527
Data columns (total 9 columns):
 #   Column                                         Non-Null Count  Dtype  
---  ------                                         --------------  -----  
 0    Mean of the integrated profile                12528 non-null  float64
 1    Standard deviation of the integrated profile  12528 non-null  float64
 2    Excess kurtosis of the integrated profile     10793 non-null  float64
 3    Skewness of the integrated profile            12528 non-null  float64
 4    Mean of the DM-SNR curve                      12528 non-null  float64
 5    Standard deviation of the DM-SNR curve        11350 non-null  float64
 6    Excess kurtosis of the DM-SNR curve           12528 non-null  float64
 7    Skewness of the DM-SNR curve                  11903 non-null  float64
 8   target_class                                   12528 non-null  float64
dtypes: float64(9)
memory usage: 881.0 KB


In [5]:
df.columns[df.isna().any()]

Index([' Excess kurtosis of the integrated profile',
       ' Standard deviation of the DM-SNR curve',
       ' Skewness of the DM-SNR curve'],
      dtype='object')

In [6]:
df.columns = [col.strip() for col in df.columns]
df.columns

Index(['Mean of the integrated profile',
       'Standard deviation of the integrated profile',
       'Excess kurtosis of the integrated profile',
       'Skewness of the integrated profile', 'Mean of the DM-SNR curve',
       'Standard deviation of the DM-SNR curve',
       'Excess kurtosis of the DM-SNR curve', 'Skewness of the DM-SNR curve',
       'target_class'],
      dtype='object')

In [7]:
df['Excess kurtosis of the DM-SNR curve'].mean()

8.333489074625241

In [8]:
df.describe()

Mean of the integrated profile  \
count                    12528.000000   
mean                       111.041841   
std                         25.672828   
min                          5.812500   
25%                        100.871094   
50%                        115.183594   
75%                        127.109375   
max                        189.734375   

       Standard deviation of the integrated profile  \
count                                  12528.000000   
mean                                      46.521437   
std                                        6.801077   
min                                       24.772042   
25%                                       42.362222   
50%                                       46.931022   
75%                                       50.979103   
max                                       91.808628   

       Excess kurtosis of the integrated profile  \
count                               10793.000000   
mean                                    0.478548   
std                                     1.064708   
min                                    -1.738021   
25%                                     0.024652   
50%                                     0.223678   
75%                                     0.473125   
max                                     8.069522   

       Skewness of the integrated profile  Mean of the DM-SNR curve  \
count                        12528.000000              12528.000000   
mean                             1.778431                 12.674758   
std                              6.208450                 29.613230   
min                             -1.791886                  0.213211   
25%                             -0.188142                  1.910535   
50%                              0.203317                  2.792642   
75%                              0.932374                  5.413253   
max                             68.101622                222.421405   

       Standard deviation of the DM-SNR curve  \
count                            11350.000000   
mean                                26.351318   
std                                 19.610842   
min                                  7.370432   
25%                                 14.404353   
50%                                 18.412402   
75%                                 28.337418   
max                                110.642211   

       Excess kurtosis of the DM-SNR curve  Skewness of the DM-SNR curve  \
count                         12528.000000                  11903.000000   
mean                              8.333489                    105.525779   
std                               4.535783                    107.399585   
min                              -3.139270                     -1.976976   
25%                               5.803063                     35.199899   
50%                               8.451097                     83.126301   
75%                              10.727927                    139.997850   
max                              34.539844                   1191.000837   

       target_class  
count  12528.000000  
mean       0.092034  
std        0.289085  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max        1.000000

In [9]:
df = df.fillna(df.median(axis=0))

In [10]:
df.describe()

Mean of the integrated profile  \
count                    12528.000000   
mean                       111.041841   
std                         25.672828   
min                          5.812500   
25%                        100.871094   
50%                        115.183594   
75%                        127.109375   
max                        189.734375   

       Standard deviation of the integrated profile  \
count                                  12528.000000   
mean                                      46.521437   
std                                        6.801077   
min                                       24.772042   
25%                                       42.362222   
50%                                       46.931022   
75%                                       50.979103   
max                                       91.808628   

       Excess kurtosis of the integrated profile  \
count                               12528.000000   
mean                                    0.443251   
std                                     0.992144   
min                                    -1.738021   
25%                                     0.057820   
50%                                     0.223678   
75%                                     0.421239   
max                                     8.069522   

       Skewness of the integrated profile  Mean of the DM-SNR curve  \
count                        12528.000000              12528.000000   
mean                             1.778431                 12.674758   
std                              6.208450                 29.613230   
min                             -1.791886                  0.213211   
25%                             -0.188142                  1.910535   
50%                              0.203317                  2.792642   
75%                              0.932374                  5.413253   
max                             68.101622                222.421405   

       Standard deviation of the DM-SNR curve  \
count                            12528.000000   
mean                                25.604827   
std                                 18.809291   
min                                  7.370432   
25%                                 14.761144   
50%                                 18.412402   
75%                                 26.473142   
max                                110.642211   

       Excess kurtosis of the DM-SNR curve  Skewness of the DM-SNR curve  \
count                         12528.000000                  12528.000000   
mean                              8.333489                    104.408308   
std                               4.535783                    104.799639   
min                              -3.139270                     -1.976976   
25%                               5.803063                     38.128424   
50%                               8.451097                     83.126301   
75%                              10.727927                    135.774973   
max                              34.539844                   1191.000837   

       target_class  
count  12528.000000  
mean       0.092034  
std        0.289085  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max        1.000000

In [11]:
df.to_csv('data/preprocessed.csv')

In [12]:
X = df[df.columns[:-1]].to_numpy()
X

array([[ 1.21156250e+02,  4.83729711e+01,  3.75484665e-01, ...,
         1.83993666e+01,  7.44987415e+00,  6.51592977e+01],
       [ 7.69687500e+01,  3.61755566e+01,  7.12897860e-01, ...,
         1.75709969e+01,  9.41465226e+00,  1.02722975e+02],
       [ 1.30585938e+02,  5.32295335e+01,  1.33408289e-01, ...,
         2.23625530e+01,  8.50836378e+00,  7.40313242e+01],
       ...,
       [ 1.16031250e+02,  4.32138464e+01,  6.63455691e-01, ...,
         1.16281494e+01,  1.70552145e+01,  3.12204325e+02],
       [ 1.35664062e+02,  4.99337494e+01, -8.99403060e-02, ...,
         2.15015050e+01,  7.39839490e+00,  6.23340175e+01],
       [ 1.20726562e+02,  5.04722564e+01,  3.46178079e-01, ...,
         1.17926025e+01,  1.76622219e+01,  3.29548016e+02]])

In [13]:
y = df['target_class'].to_numpy()
y

array([0., 0., 0., ..., 0., 0., 0.])

In [14]:
    X_scaled = scale(X)
X_scaled

array([[ 0.39398903,  0.27225212, -0.06830557, ..., -0.38309513,
        -0.19481754, -0.3745297 ],
       [-1.32725743, -1.52127273,  0.27179307, ..., -0.42713733,
         0.23837256, -0.01608212],
       [ 0.76130595,  0.98636783, -0.31230861, ..., -0.17238306,
         0.038556  , -0.28986928],
       ...,
       [ 0.19435365, -0.48635278,  0.22195739, ..., -0.74310271,
         1.92294752,  1.98287239],
       [ 0.95911539,  0.50175114, -0.53743481, ..., -0.21816269,
        -0.20616758, -0.40148965],
       [ 0.37725131,  0.58093396, -0.0978454 , ..., -0.73435917,
         2.05677923,  2.14837279]])

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, random_state=42)
X_train.shape

(9396, 8)

In [16]:
cs = [10**x for x in range(-2, 4)]
scores = []
for c in cs:
    svc = SVC(C=c, random_state=42)
    svc.fit(X_train, y_train)
    scores.append(svc.score(X_test, y_test))
scores

[0.9648786717752235,
 0.9776500638569604,
 0.979565772669221,
 0.9818007662835249,
 0.9798850574712644,
 0.9786079182630907]

In [17]:
cs

[0.01, 0.1, 1, 10, 100, 1000]

In [18]:
scores = []
for c in range(1, 11):
    svc = SVC(C=c, random_state=42)
    svc.fit(X_train, y_train)
    scores.append(svc.score(X_test, y_test))
scores

[0.979565772669221,
 0.9805236270753512,
 0.981162196679438,
 0.9821200510855683,
 0.9814814814814815,
 0.9814814814814815,
 0.9814814814814815,
 0.9814814814814815,
 0.9814814814814815,
 0.9818007662835249]

In [19]:
degrees = list(range(0, 7))
scores = []
for degree in degrees:
    svc = SVC(degree=degree, random_state=42)
    svc.fit(X_train, y_train)
    scores.append(svc.score(X_test, y_test))
scores

[0.979565772669221,
 0.979565772669221,
 0.979565772669221,
 0.979565772669221,
 0.979565772669221,
 0.979565772669221,
 0.979565772669221]

In [20]:
gammas = [10**x for x in range(-2, 3)]
scores = []
for gamma in gammas:
    svc = SVC(gamma=gamma, random_state=42)
    svc.fit(X_train, y_train)
    scores.append(svc.score(X_test, y_test))
scores

[0.9757343550446999,
 0.9792464878671775,
 0.9808429118773946,
 0.9189016602809706,
 0.9080459770114943]